### ISSUE TITLE
Home page layout breaks on small screens

### ISSUE THREAD

**Issue by mateusmtoledo** [Chatterino/website#139]
# Description
Home page layout breaks on screens less than 440px wide.

# Screenshots
<p align="center">
<img height="400" alt="Chatterino.com on iPhone SE" src="https://user-images.githubusercontent.com/98076988/213039138-8f069597-38f6-4141-b8bc-3751fa9de766.png" />
<img height="400" alt="Chatterino.com on iPhone SE" src="https://user-images.githubusercontent.com/98076988/213038627-b15e650c-270a-4d20-a93a-e40bbee9a9d5.png" />
<img height="400" alt="Chatterino.com on iPhone SE" src="https://user-images.githubusercontent.com/98076988/213038935-d1ba4ead-d8d3-4667-877f-35bbe12502c6.png" />
</p>

# Possible fixes
Header could be fixed by hiding the Chatterino text on small screens, leaving the logo visible.
The Chat component might need a little more work. A simple solution would be to scale it down on a certain breakpoint.
Most of the other sections can be fixed by adjusting margin / padding on mobile.

I'm willing to take the issue in case it is accepted.

**Comment by pajlada** [comment]
I am fine with this, given that the changes are
1) simple (Not a lot of code to review)
2) don't affect desktop viewing experiences (a desktop user is the actual target audience for the website)
3) don't add much future maintenance burden for us

Preferably the issues you've found in low-width browsers are split up into separate issues & PRs for ease of review
