### ISSUE TITLE
Add new Helix scope for managing raids

### ISSUE THREAD

**Issue by pajlada** [Chatterino/website#42]
New raids API endpoints are available in Helix, we will most likely want to use one or both of them https://discuss.dev.twitch.tv/t/new-raids-api-endpoints-are-now-in-open-beta/38866

For this to be possible, we'll need to add the `channel:manage:raids` scope to the client login page.

# File(s) to edit
 * `pages/client_login.js`

# How to test
Log in with your account on the client_login page, use the client id + oauth token and make a request to the https://dev.twitch.tv/docs/api/reference#start-a-raid and https://dev.twitch.tv/docs/api/reference#cancel-a-raid endpoints and ensure that the requests are allowed as expected. Note that your stream will need to be live when testing.

**Comment by zneix** [comment]
> Given raid/unraid already exist over irc & new helix endpoints don't work for channel editors (like irc does), we can prolly skip helix for this until improvements are made

I agree with but, but cancelling raids however is something that might be a nice touch. While it'd only work for broadcaster, not editors, it could still be a nice touch so the scope is worth implementing imo.

**Comment by Mm2PL** [comment]
I think we're wrong, IRC actually has a command for cancelling a raid:
```
> /help raid
< Usage: "/raid <channel>" - Raid another channel. Use "/unraid" to cancel the Raid. 
> /help unraid
< Usage: "/unraid" - Cancel the Raid. 
```

**Comment by zneix** [comment]
Oops. My bad, nevermind my previous comment. Let's wait then, as suggested by Prodigy.

**Comment by iProdigy** [comment]
> I think we're wrong, IRC actually has a command for cancelling a raid:

correct; tho since `/unraid` is slightly obscure, c2 could add/document a `/cancelraid` alias (tho this belongs on a separate issue tracker)

**Comment by pajlada** [comment]
I don't think we should wait with requesting the scope from users if it's a feature we could see ourselves using in the future
